Activities
gorco/gf pull request #90
Opened 2017-05-29 18:23 UTC by Victorma

+ Changed sessions to activities
+ Classes are no longer needed
+ Toolbar access fixed
+ Routes updated
+ Improved visuals
+ And many other things...

2017-05-30 16:34 UTC, gorco requested changes
Great work, some commets pending.
Awesome changes at home view

2017-05-30 16:34 UTC, gorco commented on app/public/js/controllers/activities.js
> +            $scope.game = {};
$scope.game and $scope.class are not used in this controller

2017-05-30 16:34 UTC, gorco commented on app/public/js/controllers/activity.js
If we use Activities controller now, the old Activity controller has to dissapear

2017-05-30 16:34 UTC, gorco commented on app/views/layout.jade
> +        script(src='js/controllers/activity.js')
we have to replace activity by activities (remove the activity reference)

2017-05-30 16:34 UTC, gorco commented on app/views/toolbar.jade
> +                    li(ng-if='isUser()&&hasClasses()')
we should check the role (we don't want that developers to see classes)

2017-05-30 16:34 UTC, gorco commented on app/views/toolbar.jade
> +                                a(ng-if='isDeveloper()' ng-href="#" ng-click='setSelectedClass(class, "data")') {{class.name}}
The developers can't see classes

2017-05-30 16:34 UTC, gorco commented on app/views/data/realtime/realtime.jade
> +.container-fluid.height100(ng-controller="ActivityCtrl" role="tabpanel" style="position:relative")
ActivitiesCtrl

2017-06-22 20:43 UTC, Victorma commented on app/views/toolbar.jade
> +                    li(ng-if='isUser()&&hasClasses()')
Fixed in: https://github.com/e-ucm/rage-analytics-frontend/pull/90/commits/5353294c7dba6c4720c637a730bf89ca7c7cbfb0

2017-06-22 20:43 UTC, Victorma commented on app/views/toolbar.jade
> +                                a(ng-if='isDeveloper()' ng-href="#" ng-click='setSelectedClass(class, "data")') {{class.name}}
Fixed in: https://github.com/e-ucm/rage-analytics-frontend/pull/90/commits/5353294c7dba6c4720c637a730bf89ca7c7cbfb0

2017-06-22 20:44 UTC, Victorma commented on app/views/data/realtime/realtime.jade
> +.container-fluid.height100(ng-controller="ActivityCtrl" role="tabpanel" style="position:relative")
Fixed in: https://github.com/e-ucm/rage-analytics-frontend/pull/90/commits/0edb046efc1121fa233acb2cd3d9afd7dd93ff4f

2017-06-22 20:45 UTC, Victorma commented on app/views/layout.jade
> +        script(src='js/controllers/activity.js')
Fixed in: https://github.com/e-ucm/rage-analytics-frontend/pull/90/commits/572bff82cfdb94cdb0df0d32cef2344ce44ca856

2017-06-22 20:46 UTC, Victorma commented on app/public/js/controllers/activity.js
The activity-list controller manages the creation and deletion. The activity manages the modification and realtime start and stop.

2017-06-22 20:47 UTC, Victorma commented on app/public/js/controllers/activities.js
> +            $scope.game = {};
Removed in: https://github.com/e-ucm/rage-analytics-frontend/pull/90/commits/572bff82cfdb94cdb0df0d32cef2344ce44ca856

2017-06-26 08:18 UTC, gorco commented
I'm testing the front, but when I create a new game (also if I open a game) the system throws these errors...
Backend:
![backerror](https://user-images.githubusercontent.com/5657407/27530238-1aa2e6e8-5a58-11e7-8faa-48385d96eb05.png)
Frontend
![fronterror](https://user-images.githubusercontent.com/5657407/27530241-1ca90486-5a58-11e7-99b3-a8093b430338.png)

2017-06-26 08:48 UTC, gorco commented
The developer visualizations don't load
![frontdev](https://user-images.githubusercontent.com/5657407/27531393-b87a4e2a-5a5c-11e7-80ef-075781db2cd9.png)

2017-06-26 08:51 UTC, gorco commented
As teacher, Into a Game, if I try create a activity, I can't because the frontend says that I don't have selected a game.
![fronteaerror](https://user-images.githubusercontent.com/5657407/27531564-53fa14f2-5a5d-11e7-82d0-04663a5488db.png)

2017-10-05 14:21 UTC, closed without merging